[package]
name = "query"
version = "0.1.0"
edition = "2021"

[dependencies]
protos = { path = "../../common/protos" }
trace = { path = "../../common/trace" }
tskv = { path = "../../tskv" }
models = { path = "../../common/models" }
utils = { path = "../../common/utils" }
config = { path = "../../config" }
meta = { path = "../../meta" }
coordinator = { path = "../../coordinator" }
spi = { path = "../spi" }

async-trait = { workspace = true }
datafusion = { workspace = true }
chrono = { workspace = true }
criterion = { workspace = true, features = ["async_tokio"] }
crossbeam = { workspace = true }
flatbuffers = { workspace = true }
futures = { workspace = true }
minivec = { workspace = true }
num_cpus = { workspace = true }
parking_lot = { workspace = true }
paste = { workspace = true }
pin-project = { workspace = true }
priority-queue = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
sled = { workspace = true }
snafu = { workspace = true }
derive_builder = { workspace = true }
lazy_static = { workspace = true }
serde_json = { workspace = true }
object_store = { workspace = true }
url = { workspace = true }
async-recursion = { workspace = true }
tempfile = { workspace = true }
bytes = { workspace = true }

# use libc on unix like platforms to set worker priority in DedicatedExecutor
[target."cfg(unix)".dependencies.libc]
version = "0.2"

[[bench]]
harness = false
name = "aggregate_function"

[[bench]]
harness = false
name = "scalar_function"
